// <auto-generated />
namespace BookStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PublishingCompanyBookTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PublishingCompanyBookTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201712141705335_PublishingCompanyBookTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
